# Generated by Django 3.2.7 on 2021-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=50, verbose_name='По батькові')),
                ('subject', models.CharField(max_length=50, verbose_name='Назва предмету викладання')),
                ('price_per_hour', models.CharField(max_length=50, verbose_name='Ціна заняття за годину')),
                ('specialization', models.CharField(max_length=50, verbose_name='Напрямок викладання')),
                ('experience', models.CharField(max_length=50, verbose_name='Стаж роботи')),
                ('extra_information', models.TextField(verbose_name='Додаткова інформація')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачі',
            },
        ),
    ]
