# Generated by Django 3.2.7 on 2021-10-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
