# Generated by Django 3.2.7 on 2021-10-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Репетитор', 'verbose_name_plural': 'Репетитори'},
        ),
    ]
